ghg_proj <- function(path, ...) {

  suppressMessages(suppressWarnings(
    if (!require(stringr)) install.packages('stringr')
  ))
  library(stringr, quietly = TRUE)

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # create main subdirectories
  dir.create(paste0(path, '/code'), showWarnings = FALSE)
  dir.create(paste0(path, '/data/raw/gas_concentration'),
             recursive = TRUE, showWarnings = FALSE)
  dir.create(paste0(path, '/data/raw/chamber_volume'), showWarnings = FALSE)
  dir.create(paste0(path, '/keys'), showWarnings = FALSE)
  dir.create(paste0(path, '/templates'), showWarnings = FALSE)
  dir.create(paste0(path, '/instructions'), showWarnings = FALSE)


  # collect inputs and paste together as 'Parameter: Value'
  dots <- list(...)
  fields <- names(dots)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  # copy template scripts to code/
  scripts = c("110_preprocessing.R", "110_preprocessing.Rmd", "210_cleaning.R",
              "220_impute.R", "230_unit_conversions.R", "240_NOAA_merge.R",
              "310_summarize_visual.R", "320_summarize_tabular.R",
              "400_lmer_template.R", "501_flux_time_series.R",
              "502_load_time_series.R", "503_load_barplots.R")
  for (script in scripts) {
    file.copy(
      from = system.file(package = 'gaseous', paste0('scripts/templates/', script)),
      to = paste0(path, '/code/', script)
    )
  }
  # copy chamber vol template to templates/
  file.copy(
    from = system.file(package = 'gaseous', 'templates/chamber_volume_template.xlsx'),
    to = paste0(path, '/templates/chamber_volume_template.xlsx')
  )
  # copy instructions to instructions/
  file.copy(
    from = system.file(package = 'gaseous', 'instructions/workflow_instructions.pptm'),
    to = paste0(path, '/instructions/workflow_instructions.pptm')
  )
  # copy treatment key to keys/
  file.copy(
    from = system.file(package = 'gaseous', 'keys/treatment_key.xlsx'),
    to = paste0(path, '/keys/treatment_key.xlsx')
  )


  # if data path was specified, get the raw data from that folder and put it
  # in the new data directory
  if (!dots[["existing_data"]] == "") {

    old_raw_path <- dirname(dirname(dirname(dirname(dots[["existing_data"]]))))
    old_raw_files_full <- list.files(
      path = old_raw_path,
      recursive = TRUE,
      full.names = TRUE
    )
    old_raw_files_relative <- list.files(
      path = old_raw_path,
      recursive = TRUE
    )

    for (i in 1:length(old_raw_files_full)) {
      to = paste0(path, '/data/00_raw/', old_raw_files_relative[i])
      if (!dir.exists(dirname(to))) dir.create(dirname(to), recursive = TRUE)
      file.copy(from = old_raw_files_full[i],
                to = to)
    }

  } else {
    # get site names
    site_names_ls <- dots[['sites']]
    site_names_ls <- str_remove_all(site_names_ls, '[:space:]')
    site_names_ls <- str_split(site_names_ls, ',', simplify = TRUE)

    # create directories for each site in data/raw/.../
    for (site in site_names_ls) {
      dir.create(paste0(path, '/data/00_raw/gas_concentration/', site),
                 showWarnings = FALSE)
      dir.create(paste0(path, '/data/00_raw/chamber_volume/', site),
                 showWarnings = FALSE)
    }
  }


  # generate header for file
  header <- c(
    "# This file was generated by a call to 'gaseous::ghg_proj()'.",
    "# The following inputs were received:",
    ""
  )

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to index file
  writeLines(contents, con = file.path(path, "INDEX"))
}
